apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongodb-pv-15mi
spec:
  capacity: 
    storage: 15Mi
  accessModes:
    - ReadWriteOnce
    - ReadOnlyMany
  persistentVolumeReclaimPolicy: Delete
  hostPath:
    path: /tmp/mongodb
