/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var pb_address_pb = require('../pb/address_pb.js');
goog.exportSymbol('proto.consumerdata.Customer', null, global);
goog.exportSymbol('proto.consumerdata.CustomerType', null, global);

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.consumerdata.Customer = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.consumerdata.Customer.repeatedFields_, null);
};
goog.inherits(proto.consumerdata.Customer, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.consumerdata.Customer.displayName = 'proto.consumerdata.Customer';
}
/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.consumerdata.Customer.repeatedFields_ = [2];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.consumerdata.Customer.prototype.toObject = function(opt_includeInstance) {
  return proto.consumerdata.Customer.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.consumerdata.Customer} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.consumerdata.Customer.toObject = function(includeInstance, msg) {
  var f, obj = {
    username: jspb.Message.getFieldWithDefault(msg, 1, ""),
    emailAddressList: jspb.Message.getRepeatedField(msg, 2),
    type: jspb.Message.getFieldWithDefault(msg, 3, 0),
    address: (f = msg.getAddress()) && pb_address_pb.Address.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.consumerdata.Customer}
 */
proto.consumerdata.Customer.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.consumerdata.Customer;
  return proto.consumerdata.Customer.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.consumerdata.Customer} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.consumerdata.Customer}
 */
proto.consumerdata.Customer.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setUsername(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.addEmailAddress(value);
      break;
    case 3:
      var value = /** @type {!proto.consumerdata.CustomerType} */ (reader.readEnum());
      msg.setType(value);
      break;
    case 4:
      var value = new pb_address_pb.Address;
      reader.readMessage(value,pb_address_pb.Address.deserializeBinaryFromReader);
      msg.setAddress(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.consumerdata.Customer.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.consumerdata.Customer.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.consumerdata.Customer} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.consumerdata.Customer.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getUsername();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getEmailAddressList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      2,
      f
    );
  }
  f = message.getType();
  if (f !== 0.0) {
    writer.writeEnum(
      3,
      f
    );
  }
  f = message.getAddress();
  if (f != null) {
    writer.writeMessage(
      4,
      f,
      pb_address_pb.Address.serializeBinaryToWriter
    );
  }
};


/**
 * optional string username = 1;
 * @return {string}
 */
proto.consumerdata.Customer.prototype.getUsername = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/** @param {string} value */
proto.consumerdata.Customer.prototype.setUsername = function(value) {
  jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * repeated string email_address = 2;
 * @return {!Array<string>}
 */
proto.consumerdata.Customer.prototype.getEmailAddressList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 2));
};


/** @param {!Array<string>} value */
proto.consumerdata.Customer.prototype.setEmailAddressList = function(value) {
  jspb.Message.setField(this, 2, value || []);
};


/**
 * @param {!string} value
 * @param {number=} opt_index
 */
proto.consumerdata.Customer.prototype.addEmailAddress = function(value, opt_index) {
  jspb.Message.addToRepeatedField(this, 2, value, opt_index);
};


proto.consumerdata.Customer.prototype.clearEmailAddressList = function() {
  this.setEmailAddressList([]);
};


/**
 * optional CustomerType type = 3;
 * @return {!proto.consumerdata.CustomerType}
 */
proto.consumerdata.Customer.prototype.getType = function() {
  return /** @type {!proto.consumerdata.CustomerType} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/** @param {!proto.consumerdata.CustomerType} value */
proto.consumerdata.Customer.prototype.setType = function(value) {
  jspb.Message.setProto3EnumField(this, 3, value);
};


/**
 * optional Address address = 4;
 * @return {?proto.consumerdata.Address}
 */
proto.consumerdata.Customer.prototype.getAddress = function() {
  return /** @type{?proto.consumerdata.Address} */ (
    jspb.Message.getWrapperField(this, pb_address_pb.Address, 4));
};


/** @param {?proto.consumerdata.Address|undefined} value */
proto.consumerdata.Customer.prototype.setAddress = function(value) {
  jspb.Message.setWrapperField(this, 4, value);
};


proto.consumerdata.Customer.prototype.clearAddress = function() {
  this.setAddress(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.consumerdata.Customer.prototype.hasAddress = function() {
  return jspb.Message.getField(this, 4) != null;
};


/**
 * @enum {number}
 */
proto.consumerdata.CustomerType = {
  REGULAR: 0,
  MEMBER: 1,
  SPONSOR: 2
};

goog.object.extend(exports, proto.consumerdata);
