apiVersion: v1
kind: Pod
metadata:
  name: kubia-manual
spec:
  containers:
  - image: abidali23/kubia
    name: kubia
    imagePullPolicy: Never
    ports:
    - containerPort: 8080
      protocol: TCP